POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Second User",
    "username": "user2",
    "password": "pass"
}

### Get all users
GET http://localhost:3003/api/users
