### GET
GET http://localhost:3000/api/diaries

### POST
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
    "date": "2023-01-01",
    "weather": "sunny",
    "visibility": "good",
    "comment": "PGood stuff but scary"
}
