POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jake",
    "name": "Jake the Snake",
    "password": "horriblepassword"
}

### Get all users
GET http://localhost:3001/api/users
