### GetAll
GET http://localhost:3001/api/diagnoses


### GetAll
GET http://localhost:3001/api/patients

### GetOne
GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667




### POST
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Mike",
    "dateOfBirth": "1980-01-01",
    "ssn": "5545646213",
    "gender": "Male",
    "occupation": "Dev"
}