### POST
POST http://localhost:3003/api/blogs
Authorization: do a test login to get a token
Content-Type: application/json

{
    "author": "SHOULDNT WORK",
    "title": "of things not tried",
    "url": "https://falalala.com"
}

### GET
GET http://localhost:3003/api/blogs


### GET One
GET http://localhost:3003/api/blogs/63ea7bbccc5acd2429c05665


### Delete entry
DELETE http://localhost:3003/api/blogs/63efc08c04c6f66c9c259318
Authorization: do a test login to get a token