### POST
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: 
{
    "author": "joe gain",
    "title": "another blog",
    "url": "https://tirexample.com"
}

### GET
GET http://localhost:3003/api/blogs


### GET One
GET http://localhost:3003/api/blogs/63eceac08eeb3238ec5c36c8