GET http://localhost:3001/api/persons/

### get a single person
GET http://localhost:3001/api/persons/63e3f91aea2af11151ec6300

### delete (provide existing id)
DELETE http://localhost:3001/api/persons/63e3fbd20b293e67d34c

### working send
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Mike Vautour", 
    "number": "905-3333333"
}

### UPDATE
PUT http://localhost:3001/api/persons/63e67f16f37b6f01b91103af
Content-Type: application/json

{ 
    "name": "Mike Via", 
    "number": "999999999999"
}

### Send missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "number": "905-333-3333"
}

### Send missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "Mike Vautour" 
}